version: '3.8'

services:
  limestone:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - redis_cache:/data
  

volumes:
  postgres:
    driver: local
  redis_cache:
    driver: local