load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "user",
    srcs = ["user.go"],
    importpath = "github.com/mnadev/limestone/storage",
    visibility = ["//visibility:public"],
)